environment: production
image: ffc-elm-compliance
name: ffc-elm-compliance
namespace: ffc-elm
auth:
imagePullSecret: myregistrykey

service:
  port: 443
  type: NodePort

container:
  priorityClassName: low
  imagePullPolicy: Always
  redeployOnChange: update this field to force a change
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 80Mi
  limitCpu: 80m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always

ingress:
  endPoint: ffc-elm-compliance
  server: localhost

replicas: 1
minReadySeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
