version: '3.7'

# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  app:
    build:
      target: development
    image: ffc-elm-compliance-development
    ports:
      - "3004:3004"
      - "9229:9229"
    volumes:
      - ./.git/:/home/node/.git/ # Git is required by Jest file watcher
      - ./app/:/home/node/app/
      - ./test/:/home/node/test/
      - ./test-output/:/home/node/test-output/
      - ./jest.config.js:/home/node/jest.config.js
      - ./jest.setup.js:/home/node/jest.setup.js
      - ./package.json:/home/node/package.json
      - ./package-lock.json:/home/node/package-lock.json
