version: '3.7'

services:
  app:
    build:
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    environment:
      LOG_REQUESTS: ${LOG_REQUESTS:-true}
    image: ffc-elm-compliance
    depends_on:
      - ffc-demo-compliance-postgres
    networks:
      default:
        aliases:
          - ffc-elm-compliance

  ffc-demo-compliance-postgres:
    image: postgres:11.4-alpine
    env_file:
      - variables/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}