{{- if not .Values.ingress.alb }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.auth }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: ffc-elm-compliance-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ffc-elm-compliance"
{{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override {{.Values.name }}.default.svc.cluster.local:{{ .Values.service.port }};
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
  name: {{ quote .Values.name }}
  namespace: {{ quote .Values.namespace }}
spec:
  rules:
{{- if .Values.ingress.endpoint }}
  - host: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server }}
    http:
{{ else }}
  - http:
{{- end }}
      paths:
      - path: /?(.*)
        backend:
          serviceName: {{ quote .Values.name }}
          servicePort: {{ .Values.service.port }}
{{- end }}
