apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- if .Values.ingress.alb }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.endpoint }}.{{ .Values.ingress.server}}
  {{- end }}
  name: {{ quote .Values.name }}
  labels:
    app: {{ quote .Values.name }}
  namespace: {{quote .Values.namespace}}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: http
  selector:
    app: {{ quote .Values.name }}
  type: {{ quote .Values.service.type }}
